GET http://localhost:8080/api/articles

###
POST http://localhost:8080/api/articles/7/addSpecification
5
###
GET http://localhost:8080/api/articles/7

###
GET http://localhost:8080/api/articles/filterByBrand?brand=zara

###
GET http://localhost:8080/api/articles/filterByMaterial?material=bumbac

###
PUT http://localhost:8080/api/articles/7

{
  "name": "top",
  "brand": "adidas",
  "material": "tafta",
  "type": "maneca",
  "price": 3.0,
  "specifications": null,
  "orders": null,
  "warehouse": null
}

###
POST http://localhost:8080/api/articles

  {
  "name": "fusta",
  "brand": "zara",
  "material": "matase",
  "type": "lunga",
  "price": 60,
  "specifications": null,
  "orders": null,
  "warehouse": null
  }


###
DELETE http://localhost:8080/api/articles/12

###
GET http://localhost:8080/api/articles/7/specifications

###
GET http://localhost:8080/api/articles/7/orders
###

GET http://localhost:8080/api/articles/10/warehouse

###
GET http://localhost:8080/api/specifications

###
GET http://localhost:8080/api/specifications/5

###
POST http://localhost:8080/api/specifications

###
PUT http://localhost:8080/api/specifications/5

###
DELETE http://localhost:8080/api/specifications/6

###
GET http://localhost:8080/api/specifications/7/articles

###
GET http://localhost:8080/api/specifications/filterByColor?color=blue

###
GET http://localhost:8080/api/specifications/filterBySize?size=S

###PROXY
GET http://localhost:8080/api/review
###
POST http://localhost:8080/api/review/7/addArticle
7

###
POST http://localhost:8080/api/review/7/addClient
7


###
GET http://localhost:8080/api/review/7

###
POST http://localhost:8080/api/review

{
    "stars": "5 stars",
    "comment": "super!",
    "date": "09.05.2023",
    "client": null
}

###
PUT http://localhost:8080/api/review/7

{
    "stars": "4 stars",
    "comment": "super!",
    "date": "09.05.2023",
    "client": null
}

###
DELETE http://localhost:8080/api/review/8

###
GET http://localhost:8080/api/review/7/article

###
GET http://localhost:8080/api/review/7/client

###
GET http://localhost:8080/api/review/filterByStars?stars=5

###
GET http://localhost:8080/api/order

###
GET http://localhost:8080/api/order/13

###
POST /http://localhost:8080/api/order

{
    "orderNumber": 0.0,
    "totalAmount": 0.0,
    "address": "Gruia 57",
    "date": "12.12.2022",
    "articles": [],
    "client": null,
    "employee": null,
    "paymentMethod": "cash"
}

###
POST http://localhost:8080/api/order/13/addClient
7
###
PUT http://localhost:8080/api/order/13

{
    "orderNumber": 30.0,
    "totalAmount": 100.0,
    "address": "Gruia 57",
    "date": "12.12.2022",
    "articles": [],
    "client": null,
    "employee": null,
    "paymentMethod": "cash"
}
###
DELETE http://localhost:8080/api/order/22

###
GET http://localhost:8080/api/order/13/articles

###
GET http://localhost:8080/api/order/filterByDate?date=10.12.2022

###
GET http://localhost:8080/api/order/13/client

###
GET http://localhost:8080/api/order/13/employee

###
GET http://localhost:8080/api/client

###
GET http://localhost:8080/api/client/7

###
POST http://localhost:8080/api/client

{
    "name": "Marin",
    "address": "ploiesti 30",
    "telefon": 844.6535.222,
    "orders": [13],
    "cart": null,
    "review": []
  }

###
PUT http://localhost:8080/api/client/7

{
    "name": "Marin",
    "address": "doinei 1",
    "telefon": 844.6535.222,
    "orders": [13],
    "cart": null,
    "review": []
  }

###
DELETE http://localhost:8080/api/client/8

###
GET http://localhost:8080/api/client/7/orders

###
GET http://localhost:8080/api/client/7/review

###
GET http://localhost:8080/api/client/filterByName?name=Ion

###
GET http://localhost:8080/api/courier

###
GET http://localhost:8080/api/courier/1

###
POST http://localhost:8080/api/courier

  {
    "name": "Eugen",
    "role": null,
    "salary": "1500",
    "telefon": 7947448.0,
    "orders": [],
    "warehouse": null
  }

###
PUT http://localhost:8080/api/courier/1

  {
    "name": "Eugen",
    "role": null,
    "salary": "3000",
    "telefon": 7947448.0,
    "orders": [],
    "warehouse": null
  }

###
DELETE http://localhost:8080/api/courier/2

###
GET http://localhost:8080/api/employee

###
GET http://localhost:8080/api/employee/5

###
POST http://localhost:8080/api/employee

{
    "name": "Dragos",
    "role": null,
    "salary": "1500",
    "telefon": 7947448.0,
    "orders": [],
    "warehouse": null
}

###
PUT http://localhost:8080/api/employee/5

{
    "name": "Dragos",
    "role": null,
    "salary": "800",
    "telefon": 7947448.0,
    "orders": [],
    "warehouse": null
  }

###
GET http://localhost:8080/api/employee/filterByRole?role=billing

###
DELETE http://localhost:8080/api/employee/4

###
GET http://localhost:8080/api/warehouse/6/suppliers

###
GET http://localhost:8080/api/warehouse/6/couriers

###
GET http://localhost:8080/api/warehouse/6/employees

###
GET http://localhost:8080/api/warehouse/6/articles

###
GET http://localhost:8080/api/cart

###
GET http://localhost:8080/api/cart/6

###
GET http://localhost:8080/api/cart/5/articles

###
PUT  http://localhost:8080/api/cart/5

{
    "quantity": 5.0,
    "articles": [],
    "client": null,
    "observers": null
  }

###
POST http://localhost:8080/api/cart/6/addClient
8

###

GET http://localhost:8080/api/cart/5/client

###
GET http://localhost:8080/api/supplier/5/warehouse

###
GET http://localhost:8080/api/warehouse/filteredByAddress?address=Gruia 56

###
GET http://localhost:8080/api/supplier

###
GET http://localhost:8080/api/supplier/5

###
DELETE http://localhost:8080/api/supplier/5

###
GET http://localhost:8080/api/supplier/filterByName?name=Silviu

###
GET http://localhost:8080/api/warehouse

###
GET http://localhost:8080/api/warehouse/6

###
POST http://localhost:8080/api/warehouse

###
PUT http://localhost:8080/api/warehouse/6

###
DELETE http://localhost:8080/api/warehouse/6

