GET http://localhost:8080/api/articles
###
GET http://localhost:8080/api/articles/8

GET http://localhost:8080/api/articles/findByMaterial

###
POST http://localhost:8080/api/articles/

{
  "name": "tricou",
  "brand": "adidas",
  "material": "bumbac",
  "type": "crop top",
  "price": 100,
  "cart_id": null,
  "warehouse_id": null
}


###
PUT /articles/1

###
DELETE http://localhost:8080/api/articles/8

###
GET http://localhost:8080/api/articles/7GET http://localhost:8080/api/articles/1/specifications/specifications

###
GET http://localhost:8080/api/articles/1/reviews

###
GET http://localhost:8080/api/specifications

###

GET http://localhost:8080/api/specifications/5

###
POST http://localhost:8080/api/specifications

###
PUT http://localhost:8080/api/specifications/5

###
DELETE http://localhost:8080/api/specifications/5

###
GET http://localhost:8080/api/review

###
GET http://localhost:8080/api/review/7

###
POST http://localhost:8080/api/review

###
PUT http://localhost:8080/api/review/7

###
DELETE http://localhost:8080/api/review/7

###
GET http://localhost:8080/api/order

###
GET http://localhost:8080/api/order/13

###
POST /http://localhost:8080/api/order

###
PUT http://localhost:8080/api/order/13

###
DELETE http://localhost:8080/api/order/13

###
POST http://localhost:8080/api/order/13/process

###
GET http://localhost:8080/api/client

###
GET http://localhost:8080/api/client/7

###
POST http://localhost:8080/api/client

###
PUT http://localhost:8080/api/client/7

###
DELETE http://localhost:8080/api/client/7

###
GET http://localhost:8080/api/client/7/orders

###
GET http://localhost:8080/api/client/7/reviews

###
GET http://localhost:8080/api/courier

###
GET http://localhost:8080/api/courier/1

###
POST http://localhost:8080/api/courier

###
PUT http://localhost:8080/api/courier/1

###
DELETE http://localhost:8080/api/courier/1

###
GET http://localhost:8080/api/employee

###
GET http://localhost:8080/api/employee/5

###
POST http://localhost:8080/api/employee

###
PUT http://localhost:8080/api/employee/5

###
DELETE http://localhost:8080/api/employee/5

###
GET http://localhost:8080/api/warehouse

###
GET http://localhost:8080/api/warehouse/6

###
POST http://localhost:8080/api/warehouse

###
PUT http://localhost:8080/api/warehouse/6

###
DELETE http://localhost:8080/api/warehouse/6